# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2ee6674e9f04a97fb7ba6ab8fa5e337fec05d66b58ff545b3ea7f5374f1895342662cbc1494c7ee274beddac6927c8c6cb1d8e912cd333ed4860eea3f225cf9

test:
  secret_key_base: 720c0dcbad6847e36ef7d92ad91a8865ea4dd4aa89511750bc68015f18545345cbebc461f2a3751a6ae8809d2ab3fc1dbca87ec0dba323ac5db2632960b48fd5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
